import pandas as pd
import os
from fpdf import FPDF
import io

def load_data():
    base_path = os.path.dirname(__file__)
    file_path = os.path.join(base_path, 'PSL.csv')
    df = pd.read_csv(file_path)
    return df

def get_stats(df, team_name="All Teams"):
    temp_df = df
    if team_name != "All Teams":
        temp_df = df[df['Team'] == team_name]

    batsmen = temp_df.groupby('Batter')['Batter runs'].sum().sort_values(ascending=False).head(5).to_dict()
    bowlers = temp_df[temp_df['Wickets'] > 0].groupby('Bowler')['Wickets'].count().sort_values(ascending=False).head(5).to_dict()
    
    return {
        'batsmen': batsmen,
        'bowlers': bowlers,
        'total_runs': f"{int(temp_df['Batter runs'].sum()):,}",
        'total_wickets': f"{int(temp_df['Wickets'].sum()):,}"
    }

def compare_players_logic(df, p1, p2):
    res = {}
    for p in [p1, p2]:
        p_df = df[df['Batter'] == p]
        runs = int(p_df['Batter runs'].sum())
        balls = len(p_df)
        sr = round((runs / balls) * 100, 2) if balls > 0 else 0
        res[p] = {'Runs': runs, 'SR': sr}
    return res

def predict_winner_logic(df, team1, team2, venue):
    t1_wins = len(df[(df['Winner'] == team1) & (df['venue'] == venue)])
    t2_wins = len(df[(df['Winner'] == team2) & (df['venue'] == venue)])
    
    if t1_wins > t2_wins:
        return team1, 75
    elif t2_wins > t1_wins:
        return team2, 75
    else:
        return "Tough Competition", 50

# Custom Professional PDF Generator (Crash-free)
class PSLReportPDF(FPDF):
    def header(self):
        # Top banner neon strip
        self.set_fill_color(57, 255, 20) # Neon Green
        self.rect(0, 0, 210, 8, 'F')
        
        self.ln(5)
        # Title
        self.set_font('Helvetica', 'B', 22)
        self.set_text_color(10, 10, 15) # Dark Grey
        self.cell(0, 15, "PSL AI ELITE REPORT", ln=True, align='C')
        
        self.set_font('Helvetica', 'I', 10)
        self.set_text_color(128, 128, 128)
        self.cell(0, 5, "Data-Driven Sports Analytics & Match Prediction", ln=True, align='C')
        self.ln(8)
        
        # Decorative line
        self.set_draw_color(57, 255, 20)
        self.set_line_width(1)
        self.line(15, self.get_y(), 195, self.get_y())
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by PSL AI Elite Dashboard', align='C')

def generate_pdf_report(stats, team_name, ai_data=None, comp_data=None):
    pdf = PSLReportPDF()
    pdf.add_page()
    
    # Section: Overview Cards
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(10, 10, 15)
    pdf.cell(0, 10, f"Analysis Context: {team_name}", ln=True)
    pdf.ln(2)
    
    # Stats Cards (Table Style)
    pdf.set_fill_color(240, 248, 240) # Soft Green Background
    pdf.set_draw_color(220, 220, 220)
    pdf.set_font('Helvetica', 'B', 11)
    
    pdf.cell(90, 10, "  TOTAL RUNS", border=1, fill=True)
    pdf.cell(90, 10, "  TOTAL WICKETS", border=1, fill=True, ln=True)
    
    pdf.set_font('Helvetica', 'B', 16)
    pdf.set_text_color(50, 200, 20) # Green Text
    pdf.cell(90, 12, f"  {stats['total_runs']}", border=1)
    pdf.cell(90, 12, f"  {stats['total_wickets']}", border=1, ln=True)
    pdf.ln(10)
    
    # Section: Top Performances Tables
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(10, 10, 15)
    pdf.cell(0, 10, "Top Performers (Season Insights)", ln=True)
    pdf.ln(2)
    
    # Sub-table headers
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_text_color(255, 255, 255)
    pdf.set_fill_color(30, 30, 40) # Dark Header
    
    pdf.cell(90, 8, "  BATTER (RUNS)", border=1, fill=True)
    pdf.cell(90, 8, "  BOWLER (WICKETS)", border=1, fill=True, ln=True)
    
    # Table rows
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(50, 50, 50)
    
    batsmen_list = list(stats['batsmen'].items())
    bowlers_list = list(stats['bowlers'].items())
    
    for i in range(5):
        b_text = f"  {batsmen_list[i][0]}: {batsmen_list[i][1]} runs" if i < len(batsmen_list) else "  -"
        w_text = f"  {bowlers_list[i][0]}: {bowlers_list[i][1]} wickets" if i < len(bowlers_list) else "  -"
        
        # Alternating row colors
        bg_row = (i % 2 == 0)
        pdf.set_fill_color(250, 250, 250) if bg_row else pdf.set_fill_color(255, 255, 255)
        
        pdf.cell(90, 8, b_text, border=1, fill=True)
        pdf.cell(90, 8, w_text, border=1, fill=True, ln=True)
        
    pdf.ln(10)

    # Section: AI Predictions
    if ai_data and ai_data.get('winner'):
        pdf.set_font('Helvetica', 'B', 14)
        pdf.set_text_color(10, 10, 15)
        pdf.cell(0, 10, "AI Match Prediction Analysis", ln=True)
        pdf.ln(2)
        
        pdf.set_fill_color(245, 245, 250)
        pdf.rect(15, pdf.get_y(), 180, 24, 'F')
        
        pdf.set_font('Helvetica', 'B', 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 6, f"  VENUE: {ai_data['venue']}", ln=True)
        
        pdf.set_font('Helvetica', 'B', 12)
        pdf.set_text_color(50, 200, 20)
        pdf.cell(0, 12, f"  PREDICTED WINNER: {ai_data['winner']} ({ai_data['probability']}% confidence)", ln=True)
        pdf.ln(8)

    # Section: Head-to-Head Player Comparison
    if comp_data:
        pdf.set_font('Helvetica', 'B', 14)
        pdf.set_text_color(10, 10, 15)
        pdf.cell(0, 10, "Player Head-to-Head Comparison", ln=True)
        pdf.ln(2)
        
        # Header
        pdf.set_font('Helvetica', 'B', 10)
        pdf.set_text_color(255, 255, 255)
        pdf.set_fill_color(30, 30, 40)
        pdf.cell(60, 8, "  PLAYER", border=1, fill=True)
        pdf.cell(60, 8, "  TOTAL RUNS", border=1, fill=True, align='C')
        pdf.cell(60, 8, "  STRIKE RATE", border=1, fill=True, align='C', ln=True)
        
        # Data Rows
        pdf.set_font('Helvetica', '', 10)
        pdf.set_text_color(50, 50, 50)
        bg = True
        for p_name, p_stats in comp_data.items():
            pdf.set_fill_color(250, 250, 250) if bg else pdf.set_fill_color(255, 255, 255)
            pdf.cell(60, 8, f"  {p_name}", border=1, fill=True)
            pdf.cell(60, 8, f"{p_stats['Runs']}", border=1, fill=True, align='C')
            pdf.cell(60, 8, f"{p_stats['SR']}", border=1, fill=True, align='C', ln=True)
            bg = not bg

    # Output as memory-based byte stream
    return pdf.output()